### ISSUE TITLE
Error: 'http-header-max-length' is not a known key name with bin/instance, plone.recipe.zope2instance 6.0.0

### ISSUE THREAD

**Issue by zopyx** [plone/plone.recipe.zope2instance#65] opened 2019-01-08 06:06 UTC
Plone 5.2a2, plone.recipe.zope2instance 6.0.0 (under Python 3):

```
bin/instance fg
Error: 'http-header-max-length' is not a known key name
(line 9 in file:///home/ajung/sandboxes/onkopedia_buildout-plone5/parts/instance/etc/zope.conf)
For help, use bin/instance -h
```

`bin/wsgi.py` is working as expected

**Comment by cekk** [comment] 2019-01-26 00:12
This seems fixed in 6.1.0. I had the same problem on 6.0.0 but not on 6.1.0.

**Comment by hvelarde** [comment] 2019-02-28 04:35
no, 6.1.0 doesn't solve the issue:

```console
$ bin/instance fg
Traceback (most recent call last):
  File "bin/instance", line 260, in <module>
    + sys.argv[1:]))
  File "/home/hvelarde/.buildout/eggs/plone.recipe.zope2instance-6.1.0-py3.7.egg/plone/recipe/zope2instance/ctl.py", line 869, in main
    options = ZServerCtlOptions()
NameError: name 'ZServerCtlOptions' is not defined
```

**Comment by pbauer** [comment] 2019-02-28 05:53
@hvelarde please show the config of your part `[instance]`.

**Comment by zopyx** [comment] 2019-02-28 06:00
Having the same issue with `ZServerCtlOptions` while trying to port collective.es.index...checking later during the sprint.

**Comment by zopyx** [comment] 2019-02-28 06:34
The ZServerCtlOptions error occurs also with 

https://github.com/collective/collective.es.index/blob/plone-52-python3/buildout.cfg

but with `wsgi=on` disabled.

**Comment by zopyx** [comment] 2019-02-28 06:38
The internal check for `HAS_ZSERVER` appears flaky with WSGI disabled...
[6] > /home/ajung/.buildout/eggs/plone.recipe.zope2instance-6.1.1-py3.7.egg/plone/recipe/zope2instance/ctl.py(176)<module>()
-> from ZServer.Zope2.Startup.options import ZopeOptions

(Pdb++) import ZServer
*** ModuleNotFoundError: No module named 'ZServer'
(Pdb++)

Not sure why `ZServer` module is not available.

**Comment by zopyx** [comment] 2019-02-28 06:38
In contract: WSGI mode enabled leads to a different failure:

https://github.com/plone/Products.CMFPlone/issues/2774

**Comment by pbauer** [comment] 2019-02-28 07:33
Can you please try to reproduce it with the current master of `plone.recipe.zope2instance` since it has a important change (wsgi is always on unless explicitly disabled with `wsgi=off` and running python 2)

**Comment by pbauer** [comment] 2019-02-28 08:03
`ZServer` cannot be avaibale when running on py3.

**Comment by hvelarde** [comment] 2019-03-08 04:29
@pbauer this is what I have:

```ìni
[instance]
deprecation-warnings= on
    buildout.cfg
eggs= Plone
plone.app.upgrade
${buildout:package-name}
${buildout:eggs}
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
environment-vars= zope_i18n_compile_mo_files true
PROFILE_PUBLISHER 1
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
+=  buildout.cfg
http-address= 8080
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
recipe= plone.recipe.zope2instance
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
user= admin:admin
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
wsgi= on
    buildout.cfg
zcml= ${buildout:package-name}
    https://raw.github.com/collective/buildout.plonetest/master/plone-5.2.x.cfg
 ```

**Comment by hvelarde** [comment] 2019-03-13 02:43
`plone.recipe.zope2instance = 6.1.3` seems to fix the issue.

**Comment by dataflake** [comment] 2019-04-22 15:03
This is already fixed. `wsgi = on` is the default, and the keyword `http-header-max-length` does not throw an error.

**Closed by dataflake** 2019-04-22 15:03 UTC
Labels: 01 type: bug, 21 status: confirmed, 31 needs: help
